repo_name: neural-fields-review
name: Developmental AI
tagline: Developmental AI
date: Sept 2021
favicon: favicon.ico
logo:
    main: static/images/main_logo.png
    long: static/images/main_logo.png
page_title:
    prefix: "Neural Fields"
    separator: ": "
background_image: static/images/main.jpg
organization: Brown Visual Computing Group

add_paper_form_link: https://forms.gle/JKMicvyaaekoes3w5
update_paper_form_link: https://forms.gle/LwetzG6umEyZaRAS6
