repo_name: neural-fields-review
name: Neural Fields in Visual Computing
tagline: Neural Fields in Visual Computing
date: Sept 2021
favicon: favicon.ico
logo:
    main: static/images/main_logo_new.png
    long: static/images/long_logo_new.png
page_title:
    prefix: "NeuralFields"
    separator: ": "
background_image: static/images/main.jpg
organization: Brown Visual Computing Group

add_paper_form_link: https://forms.gle/JKMicvyaaekoes3w5
update_paper_form_link: https://forms.gle/LwetzG6umEyZaRAS6
